import "@/styles/globals.css"
import { Inter } from "next/font/google"
import type React from "react"
import { ThemeProvider } from "@/components/Theme/theme-provider"
import { AuthProvider } from "@/lib/AuthContext"
import { SecuritiesProvider } from "@/lib/SecuritiesContext"
import { Sidebar } from "@/components/layout/Sidebar"
import { Metadata } from "next"

const inter = Inter({ subsets: ["latin"] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <AuthProvider>
            <SecuritiesProvider>
              <div className="min-h-screen bg-background">
                <div className="grid lg:grid-cols-[280px_1fr]">
                  <Sidebar />
                  <main>{children}</main>
                </div>
              </div>
            </SecuritiesProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  generator: 'v0.dev',
  description: "Generated by create next app",
}
