name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22' # Or your Go version

      - name: Build the application
        run: |
          # The output binary will be named 'duw-api'
          go build -o duw-api ./api/cmd/server

      - name: Set timestamp
        run: echo "RELEASE_VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Deploy files to Server
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          # The SOURCE includes the main directory and the new binary
          SOURCE: "./"
          TARGET: /var/www/duwapi/releases/${{ env.RELEASE_VERSION }}

      - name: Update symlink and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update the symlink to the new release
            ln -nfs /var/www/duwapi/releases/${{ env.RELEASE_VERSION }} /var/www/duwapi/current
            # Restart the service to run the new code
            sudo systemctl restart duw-api.service