name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Set the timestamp as a job-level environment variable
      - name: Set timestamp
        run: echo "RELEASE_VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # Step 2: Deploy files using the shared timestamp
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          # Use the environment variable set in the previous step
          TARGET: /var/www/duwapi/releases/${{ env.RELEASE_VERSION }}

      # Step 3: Update the symlink using the SAME shared timestamp
      - name: Update Symlink
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Use the environment variable for the symlink target
            ln -nfs /var/www/duwapi/releases/${{ env.RELEASE_VERSION }} /var/www/duwapi/current